spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

server:
  port: 8080
  contextPath: /api

info:
  app:
    name: Hotel Reservation Application
    version: 1.0
    contactEmail: buddhi.1986@gmail.com